### ISSUE TITLE
Can not run the demo locally

### ISSUE THREAD

**Issue by aziz** [tchatel/angular-treeRepeat#2]
I'm having a hard time playing with the demo app of yours. 
just cloned it and run the simple python server of the app directory. 
on the browser I'm getting the below error no matter what route I'm in

```
TypeError: Cannot read property 'current' of undefined
 at update (http://localhost:8886/lib/angular/angular-route.js:820:30)
    at http://localhost:8886/lib/angular/angular-route.js:806:9
    at nodeLinkFn (http://localhost:8886/lib/angular/angular.js:5435:13)
    at compositeLinkFn (http://localhost:8886/lib/angular/angular.js:4899:15)
    at compositeLinkFn (http://localhost:8886/lib/angular/angular.js:4914:13)
    at compositeLinkFn (http://localhost:8886/lib/angular/angular.js:4914:13)
    at publicLinkFn (http://localhost:8886/lib/angular/angular.js:4819:30)
    at http://localhost:8886/lib/angular/angular.js:1188:27
    at Scope.$eval (http://localhost:8886/lib/angular/angular.js:10699:28)
    at Scope.$apply (http://localhost:8886/lib/angular/angular.js:10796:23) <!-- ngView: undefined --> 
```

any idea?

**Comment by tchatel** [comment]
I don't understand, there is no python server.

You can start Node.js in the base directory, with : 

```
node scripts/web-server.js 8000
```
